a=int(input("enter first numer:"))
b=int(input("enter first number:"))
print("*****comparison operators******")
print("is equals:",a==b)
print("is not equals:",a!=b)
print("greater than:",a>b)
print("lessthan:",a<b)
print("lessthan equals:",a<=b)
print("greater than equals:",a>=b)
